version: '2'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4"
    container_name: elastic
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - homesensors
  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.2.4"
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - homesensors
  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - homesensors
  sensors:
    image: "home-sensors:latest"
    container_name: sensors
    networks:
      - homesensors

volumes:
  esdata:
    driver: local

networks:
  homesensors:      

